name: Deploy via Jump Host

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.JUMP_SSH_PK }}" > ~/.ssh/jump_rsa
          echo "${{ secrets.TARGET_SSH_PK }}" > ~/.ssh/target_rsa
          chmod 600 ~/.ssh/jump_rsa
          chmod 600 ~/.ssh/target_rsa

      - name: Add Jump Host to known hosts
        run: |
          ssh-keyscan -t rsa ${{ secrets.JUMP_HOST }} >> ~/.ssh/known_hosts

      - name: Set up SSH config
        run: |
          touch ~/.ssh/config
          echo "Host jump-host" >> ~/.ssh/config
          echo "  HostName ${{ secrets.JUMP_HOST }}" >> ~/.ssh/config
          echo "  User ${{ secrets.JUMP_USER }}" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/jump_rsa" >> ~/.ssh/config
          echo "Host target-host" >> ~/.ssh/config
          echo "  HostName ${{ secrets.TARGET_HOST }}" >> ~/.ssh/config
          echo "  User ${{ secrets.TARGET_USER }}" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/target_rsa" >> ~/.ssh/config
          echo "  ProxyJump jump-host" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          chmod 600 ~/.ssh/config
          echo "--------"
          ls -al ~/.ssh
          cat ~/.ssh/config

      - name: Test SSH connection
        run: |
          ssh target-host "sed -i 's/app: hs-test/app: hs-client/' test.txt && echo 'hi' >> test2.txt"
# ssh -i ~/.ssh/jump_rsa ${{ secrets.JUMP_USER }}@${{ secrets.JUMP_HOST }}
