name: Update YAML in B repository

on:
  push:
    branches:
      - main

jobs:
  update-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout click-helms repository
        uses: actions/checkout@v2
        with:
          repository: KaburiCoder/click-helms
          token: ${{ secrets.CLICK_HELMS_REPO_TOKEN }} # GitHub 토큰
          path: click-log
          ref: main # 기본 브랜치를 명시적으로 지정 (main이 기본 브랜치일 경우)

      - name: Update YAML file
        run: |
          sed '/client:/,/service:/s/version: ".*"/version: "${{ github.run_number }}"/' click-log/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ secrets.USER_NAME }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          cd click-log
          git add values.yaml
          git commit -m "Update version to ${{ github.run_number }}"
          git push
